appname = notes-app
httpport = ${HTTP_PORT||8080}
runmode = prod
copyrequestbody = true

EnableHTTP = false
EnableHTTPS = true
httpsport = ${HTTPS_PORT||8443}
httpscertfile = ${HTTPS_CERT||conf/cert.pem}
httpskeyfile = ${HTTPS_KEY||conf/key.pem}
